name: very_good_slide_puzzle
description: Game within a Slide Puzzle Game.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.8.0

dependencies:
  bloc: ^8.0.1
  bonfire: ^2.2.5
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flame: ^1.0.0
  flame_audio: ^1.0.0
  flame_tiled: ^1.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  gap: ^2.0.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  just_audio: ^0.9.18
  platform: ^3.1.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.17

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/audio_control/

    # tiles
    - assets/tiles/
    - assets/images/tiles/

    # sprites
    - assets/images/sprites/chara/
    - assets/images/sprites/plants/multiplant/
    - assets/images/sprites/plants/windplant/
    - assets/images/sprites/plants/blueflower/
    - assets/images/sprites/plants/waveplant/
    - assets/images/sprites/plants/smallplant/
    - assets/images/sprites/plants/plant/
    - assets/images/sprites/slime/green/
    - assets/images/sprites/slime/orange/
    - assets/images/sprites/person/
    - assets/images/sprites/bandit/
    - assets/images/sprites/fire/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
